name: Rusted Blockchain CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: rust:latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: cargo test --verbose

  build:
    runs-on: rust:latest
    name: Build
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - run: cargo build --verbose
        name: Build
